name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Debug and Release
    runs-on: windows-2022

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H%M%S')"

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Debug
        run: |
          msbuild re4_tweaks.sln /p:Configuration=Debug /p:PostBuildEventUseInBuild=false

      - name: Remove VERBOSE
        shell: bash
        run: |
          sed -i "s/#define VERBOSE//" dllmain/dllmain.h

      - name: Build Release
        run: |
          msbuild re4_tweaks.sln /p:Configuration=Release /p:PostBuildEventUseInBuild=false

      - name: Create default configuration file
        shell: bash
        run: |
          head -n -1 settings/settings_string.h | tail -n +3 > dinput8.ini
          

      - name: Copy english subtitle data files
        shell: bash
        run: |
          cp -r external/EnglishSubtitleData/Bin32/re4_tweaks/ Debug/re4_tweaks/
          cp -r external/EnglishSubtitleData/Bin32/re4_tweaks/ Release/re4_tweaks/

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: |
            Debug/dinput8.dll
            Debug/re4_tweaks/
            Release/dinput8.dll
            Release/re4_tweaks/
            dinput8.ini
          name: re4_tweaks_${{ github.head_ref || github.ref_name }}_${{ steps.date.outputs.date }}
